drop table user if exists;

create table user (
    id integer generated by default as identity primary key,
    username varchar(20) not null,
    password varchar(20) not null,
    email varchar(80),
    qq varchar(15),
    phone varchar(20)
);